<section class="epic-section">
<header>
	<h2>Build Your Validator!</h2>
</header>
<article>
	<p>
		Duis kale chips culpa mcsweeney's. Proident seitan veniam,
		mollit mumblecore culpa sunt mlkshk. Nostrud irony mcsweeney's
		consequat ennui. Keffiyeh selvage fixie eu, iphone sustainable
		eiusmod four loko mollit proident quinoa ullamco freegan chambray.
		Post-ironic laboris deserunt mustache, yr occupy pinterest.
		Twee dreamcatcher bespoke laboris farm-to-table. Officia jean
		shorts velit nisi kogi, accusamus mlkshk ut gluten-free
		farm-to-table brunch.
	</p>

	<p>
		Vice trust fund portland biodiesel fanny pack nisi, beard mollit.
		Mlkshk et +1 put a bird on it ethical, PBR vegan pitchfork.
		Officia direct trade ullamco sustainable ut, master cleanse lo-fi
		et beard whatever leggings. Delectus et marfa, pickled est
		mumblecore flexitarian. Tattooed cardigan pop-up readymade,
		williamsburg flexitarian aliquip forage mixtape dreamcatcher placeat
		veniam. Delectus stumptown voluptate aesthetic cray. Minim viral
		skateboard organic forage.
	</p>
</article>
<form>
	<ul class="demo-elements">
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="text-one" class="epic-label">Text Input:</label></li>
				<li><input type="text" name="text-one" id="text-one" class="epic-text"></li>
				<li>
					<div class="option-tabs">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters-tab">Validate Characters</a></li>
							<li><a href="#text-validate-on-event-tab">Event Validation</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters-tab">
							<ul>
								<li>
									<label for="text-one" class="epic-label">Forbid Special Chars [!@#$%^&*/\<>]</label>
									<input type="checkbox" class="special-chars epic-cbx">
								</li>
							</ul>
						</div>
						<div id="text-validate-on-event-tab">
							<ul>
								<li>
									<label class="epic-label">Validate on Focus Out</label>
									<input type="checkbox" class="focus-out epic-cbx">
								</li>
								<li>
									<label class="epic-label">Validate on Focus In</label>
									<input type="checkbox" class="focus-in epic-cbx">
								</li>
								<li>
									<label class="epic-label">Validate on KeyPress</label>
									<input type="checkbox" class="keystroke epic-cbx">
								</li>
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="email-one" class="epic-label">Email Input:</label></li>
				<li><input type="email" name="email-one" id="email-one" class="epic-text"></li>
				<li>
					<div class="option-tabs">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="password-one" class="epic-label">Password Input:</label></li>
				<li><input type="password" name="password-one" id="password-one" class="epic-password"></li>
				<li>
					<div class="option-tabs">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="password-two" class="epic-label">Password Input - Confirmation:</label></li>
				<li><input type="password" name="password-one" id="password-two" class="epic-password"></li>
				<li>
					<div class="option-tabs">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="textarea-one" class="epic-label">Text Area:</label> </li>
				<li><textarea id="textarea-one" class="epic-text"></textarea></li>
				<li>
					<div class="option-tabs textarea">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="textarea-one" class="epic-label">Button Input:</label></li>
				<li><input type="button" value="Submit-button" class="epic-button"></li>
				<li>
					<div class="option-tabs button">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
		<li>
			<ul class="demo-wrapper">
				<li class="options-header">Options</li>
				<li><label for="textarea-one" class="epic-label">Submit Input:</label></li>
				<li><input type="button" value="Submit-button" class="epic-button"></li>
				<li>
					<div class="option-tabs button">
						<ul class="options">
							<li><a href="#text-required-tab">Required</a></li>
							<li><a href="#text-validate-characters">Validate Characters</a></li>
						</ul>

						<div id="text-required-tab">
							<label for="text-one" class="epic-label">Required</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>

						<div id="text-validate-characters">
							<label for="text-one" class="epic-label">Validate Characters</label>
							<input type="checkbox" class="required-cbx epic-cbx">
						</div>
					</div>
				</li>
			</ul>
		</li>
	</ul>
</form>
<div class="clearfix-30"></div>
</section>