<!DOCTYPE html>
<html lang="en">
<head>
	<title>epicValidator jQuery Plugin</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1">
	<meta name="description" content="epicValidator jQuery Plugin. Perform advanced form validation through an easy to use interface.">
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>
	<body>
		<header id="site-header">
			<h1>epicValidator.js</h1>
			<nav>
				<a>About</a>
				<a>Basic Usage</a>
				<a href="/docs">Documentation</a>
				<a href="/build-your-validator">Build Your Plugin</a>
				<a>Feedback</a>
			</nav>
		</header>
		<section id="main-content">
			<?php echo $this->layout()->content; ?>
		</section>
		<div id="crosshairs"></div>
	</body>
</html> 